"""Catalog of legal document templates for the drafting UI."""

CATEGORIES = [
    {"id": "all", "label": "All Templates", "icon": "file-text"},
    {"id": "contracts", "label": "Contracts", "icon": "file-signature"},
    {"id": "corporate", "label": "Corporate", "icon": "building"},
    {"id": "litigation", "label": "Litigation", "icon": "gavel"},
    {"id": "property", "label": "Property", "icon": "home"},
    {"id": "employment", "label": "Employment", "icon": "briefcase"},
    {"id": "family", "label": "Family", "icon": "users"},
    {"id": "constitutional", "label": "Constitutional", "icon": "scale"},
]

TEMPLATES = [
    {
        "id": "nda",
        "title": "Non-Disclosure Agreement (NDA)",
        "description": "Protect confidential information shared between parties. Suitable for business partnerships, employment, and consulting arrangements.",
        "category": "contracts",
        "complexity": "Simple",
        "estimatedPages": 3,
        "popular": True,
        "languages": ["EN", "FR"],
    },
    {
        "id": "lease",
        "title": "Residential Lease Agreement",
        "description": "Standard rental agreement for residential property. Covers rent, duration, obligations of landlord and tenant.",
        "category": "property",
        "complexity": "Moderate",
        "estimatedPages": 6,
        "popular": True,
        "languages": ["EN", "FR"],
    },
    {
        "id": "employment",
        "title": "Employment Contract",
        "description": "Comprehensive employment agreement covering role, compensation, benefits, and termination clauses per the Labour Code.",
        "category": "employment",
        "complexity": "Moderate",
        "estimatedPages": 8,
        "popular": True,
        "languages": ["EN", "FR"],
    },
    {
        "id": "service-agreement",
        "title": "Service Agreement",
        "description": "Define scope of work, deliverables, timelines, and payment terms between a service provider and client.",
        "category": "contracts",
        "complexity": "Moderate",
        "estimatedPages": 5,
        "languages": ["EN", "FR"],
    },
    {
        "id": "incorporation",
        "title": "Articles of Incorporation (SARL)",
        "description": "Documents required to establish a Société à Responsabilité Limitée (SARL) under OHADA law.",
        "category": "corporate",
        "complexity": "Complex",
        "estimatedPages": 14,
        "popular": True,
        "languages": ["FR", "EN"],
    },
    {
        "id": "shareholder",
        "title": "Shareholders Agreement",
        "description": "Govern relationships between shareholders — share ownership, voting rights, dividends, and exit provisions.",
        "category": "corporate",
        "complexity": "Complex",
        "estimatedPages": 18,
        "languages": ["EN", "FR"],
    },
    {
        "id": "sale-property",
        "title": "Property Sale Agreement",
        "description": "Transfer ownership of real estate with clearly defined conditions, price, and timelines for completion.",
        "category": "property",
        "complexity": "Moderate",
        "estimatedPages": 7,
        "languages": ["EN", "FR"],
    },
    {
        "id": "divorce-petition",
        "title": "Divorce Petition",
        "description": "Initiate formal divorce proceedings. Includes grounds for divorce, asset division, and custody considerations.",
        "category": "family",
        "complexity": "Complex",
        "estimatedPages": 10,
        "languages": ["EN", "FR"],
    },
    {
        "id": "court-petition",
        "title": "Court Petition (Civil)",
        "description": "Formal petition to initiate civil proceedings. Structured to meet court filing requirements.",
        "category": "litigation",
        "complexity": "Moderate",
        "estimatedPages": 4,
        "languages": ["EN", "FR"],
    },
    {
        "id": "affidavit",
        "title": "Statutory Declaration / Affidavit",
        "description": "Sworn statement for use in legal proceedings. Admissible as evidence in Cameroonian courts.",
        "category": "litigation",
        "complexity": "Simple",
        "estimatedPages": 2,
        "popular": True,
        "languages": ["EN", "FR"],
    },
    {
        "id": "power-attorney",
        "title": "Power of Attorney",
        "description": "Grant another person authority to act on your behalf in legal or financial matters.",
        "category": "contracts",
        "complexity": "Simple",
        "estimatedPages": 2,
        "languages": ["EN", "FR"],
    },
    {
        "id": "marriage-contract",
        "title": "Marriage Contract (Matrimonial Regime)",
        "description": "Define the matrimonial property regime — community of property or separation of assets.",
        "category": "family",
        "complexity": "Moderate",
        "estimatedPages": 5,
        "languages": ["EN", "FR"],
    },
    {
        "id": "constitutional-petition",
        "title": "Constitutional Challenge Petition",
        "description": "Challenge the constitutionality of a law or administrative act before the Constitutional Council.",
        "category": "constitutional",
        "complexity": "Complex",
        "estimatedPages": 12,
        "languages": ["EN", "FR"],
    },
    {
        "id": "termination",
        "title": "Termination of Employment Letter",
        "description": "Formally notify an employee of contract termination with legally compliant reasoning and notice period.",
        "category": "employment",
        "complexity": "Simple",
        "estimatedPages": 2,
        "languages": ["EN", "FR"],
    },
]
